version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db

  express-app:
    build: ./server
    container_name: formation-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  react-app:
    build: ./client
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mongo-data: